# Generated by Django 2.1 on 2018-10-15 14:53

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.TextField(verbose_name=lists.models.List),
        ),
    ]
